routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DemoController; 
use App\Http\Controllers\DepartmentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
//  });

Route::get('/', [DemoController::class,'index']);

// Route::get('/contact', function () {
//     return view('contact');
// });
Route::get('/contact',[DemoController::class,'contactus']);

Route::get('/about', function () {
    return view('about');
});

Route::get('/depart', function () {
    return view('departmentdashboard');
});

Route::get('/plain', function () {
    return view('plain');
}); 

Route::get('/login',[DemoController::class,'login']);

// Route::get('/welcome',[DemoController::class,'welcomepage'])




Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();


Route::resource('department', DepartmentController::class);

app/Models/Departments.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Departments extends Model
{
    protected $table = 'departments';
    protected $primaryKey = 'id';
    protected $fillable = ['dep_name', 'dep_head_id'];

}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;
use App\Models\Departments;
use Illuminate\Http\Request;


class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Departments::latest()->paginate(5);
    
        return view('departments.index',compact('departments'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
     
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departments.create');
    }
 /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'dep_name' => 'required',
            'dep_head_id' => 'required',
        ]);
    
        Departments::create($request->all());
     
        return redirect()->route('department.index')
                        ->with('success','Department created successfully.');
    }
     
    /**
     * Display the specified resource.
     *
     * @param  \App\Departments  $departments
     * @return \Illuminate\Http\Response
     */
    public function show( $dep_id)
    {
        $departments=Departments::findorfail($dep_id);
        return view('departments.show',compact('departments'));
    } 
 /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Departments  $departments
     * @return \Illuminate\Http\Response
     */
    public function edit( $dep_id)
    {
        $departments=Departments::findorfail($dep_id);
        return view('departments.edit',compact('departments'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $departments
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $dep_id)
    {
        $request->validate([
            'dep_name' => 'required',
            'dep_head_id' => 'required',
        ]);
        $departments=Departments::findorfail($dep_id);
    
        $departments->update($request->all());
    
        return redirect()->route('department.index')
                        ->with('success','Department updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy( $dep_id)
    {
        //return $dep_id; 
        $departments=Departments::findorfail($dep_id);
        $departments->delete();
    
        return redirect()->route('department.index')
                        ->with('success','Department deleted successfully');
    }
}

resources/views/departments/create.blade.php
@extends('departments.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Department</h2>
        </div>
        <div class="pull-right">
          <br>  <a class="btn btn-primary" href="{{ route('department.index') }}"> Back</a> <br>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('department.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
               <br> <strong>Department Name:</strong> <br>
                <input type="text" name="dep_name" class="form-control" placeholder="dep_name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
               <br> <strong>Department Head Id:</strong> <br>
               <input type="number" name="dep_head_id" class="form-control" placeholder="Enter Department Head ID">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <br>  <button type="submit" class="btn btn-primary">ADD</button> <br>
        </div>
    </div>
   
</form>
@endsection

resources/views/departments/edit.blade.php
@extends('departments.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Department</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('department.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('department.update',$departments->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Department Name:</strong>
                    <input type="text" name="dep_name" value="{{ $departments->dep_name }}" class="form-control" placeholder="Enter the Name of the Department">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Department Head Id</strong>
                    <input type="text" name="dep_head_id" value="{{ $departments->dep_head_id }}" class="form-control" placeholder="Enter the Department Head id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
    @endsection

resources/views/departments/index.blade.php
@extends('departments.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Departments</h2>
            </div>
            <div class="pull-right">
              <br>  <a class="btn btn-success" href="{{ route('department.create') }}"> Create New Department</a></br>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
       <br> <div class="alert alert-success"></br>
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
      <br>  <tr>
            <th>No.</th>
            <th> Department Name</th>
            <th>Department Head Id</th>
            <th width="280px">Action</th>
        </tr> <br>
        @foreach ($departments as $department)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $department->dep_name }}</td>
            <td>{{ $department->dep_head_id }}</td>
            <td>
                
                <a class="btn btn-info" href="{{ route('department.show',$department->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('department.edit',$department->id) }}">Edit</a>
             
                <form action="{{ route('department.destroy',$department->id) }}" method="POST">

                @csrf
                @method('DELETE')
  
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $departments->links() !!}
  
@endsection 

resources/views/departments/layout.blade.php
<html>
<head>
    <title>Departments</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
  
</body>
</html>

resources/views/departments/show.blade.php
@extends('departments.layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Departments</h2>
            </div>
            <div class="pull-right">
              <br>  <a class="btn btn-primary" href="{{ route('department.index') }}"> Back</a> <br>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
               <br> <strong>Department Name:</strong> <br>
                {{ $departments->dep_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <br>  <strong>Department Head Id:</strong> <br>
                {{ $departments->dep_head_id }}
            </div>
        </div>
    </div>
@endsection